
import { VocabularyItem } from './types';

export const VOCABULARY_LIST: VocabularyItem[] = [
  { japanese: 'こんにちは', hiragana: 'こんにちは', romaji: 'Konnichiwa', vietnamese: 'Xin chào' },
  { japanese: 'ありがとう', hiragana: 'ありがとう', romaji: 'Arigatou', vietnamese: 'Cảm ơn' },
  { japanese: 'すみません', hiragana: 'すみません', romaji: 'Sumimasen', vietnamese: 'Xin lỗi' },
  { japanese: 'はい', hiragana: 'はい', romaji: 'Hai', vietnamese: 'Vâng / Đúng' },
  { japanese: 'いいえ', hiragana: 'いいえ', romaji: 'Iie', vietnamese: 'Không' },
  { japanese: 'おはよう', hiragana: 'おはよう', romaji: 'Ohayou', vietnamese: 'Chào buổi sáng' },
  { japanese: 'こんばんは', hiragana: 'こんばんは', romaji: 'Konbanwa', vietnamese: 'Chào buổi tối' },
  { japanese: 'さようなら', hiragana: 'さようなら', romaji: 'Sayounara', vietnamese: 'Tạm biệt' },
  { japanese: 'お願いします', hiragana: 'おねがいします', romaji: 'Onegaishimasu', vietnamese: 'Làm ơn / Xin vui lòng' },
  { japanese: 'ごめんなさい', hiragana: 'ごめんなさい', romaji: 'Gomennasai', vietnamese: 'Tôi xin lỗi' },
  { japanese: '日本', hiragana: 'にほん', romaji: 'Nihon', vietnamese: 'Nhật Bản' },
  { japanese: '私', hiragana: 'わたし', romaji: 'Watashi', vietnamese: 'Tôi' },
  { japanese: '学生', hiragana: 'がくせい', romaji: 'Gakusei', vietnamese: 'Học sinh' },
  { japanese: '先生', hiragana: 'せんせい', romaji: 'Sensei', vietnamese: 'Giáo viên' },
  { japanese: '犬', hiragana: 'いぬ', romaji: 'Inu', vietnamese: 'Con chó' },
  { japanese: '猫', hiragana: 'ねこ', romaji: 'Neko', vietnamese: 'Con mèo' },
  { "japanese": "今日", "hiragana": "きょう", "romaji": "Kyou", "vietnamese": "Hôm nay" },
  { "japanese": "明日", "hiragana": "あした", "romaji": "Ashita", "vietnamese": "Ngày mai" },
  { "japanese": "昨日", "hiragana": "きのう", "romaji": "Kinou", "vietnamese": "Hôm qua" },
  { "japanese": "時間", "hiragana": "じかん", "romaji": "Jikan", "vietnamese": "Thời gian" },
  { "japanese": "学校", "hiragana": "がっこう", "romaji": "Gakkou", "vietnamese": "Trường học" },
  { "japanese": "友達", "hiragana": "ともだち", "romaji": "Tomodachi", "vietnamese": "Bạn bè" },
  { "japanese": "食べ物", "hiragana": "たべもの", "romaji": "Tabemono", "vietnamese": "Đồ ăn" },
  { "japanese": "飲み物", "hiragana": "のみもの", "romaji": "Nomimono", "vietnamese": "Đồ uống" },
  { "japanese": "水", "hiragana": "みず", "romaji": "Mizu", "vietnamese": "Nước" },
  { "japanese": "天気", "hiragana": "てんき", "romaji": "Tenki", "vietnamese": "Thời tiết" },
  { "japanese": "雨", "hiragana": "あめ", "romaji": "Ame", "vietnamese": "Mưa" },
  { "japanese": "電車", "hiragana": "でんしゃ", "romaji": "Densha", "vietnamese": "Tàu điện" },
  { "japanese": "駅", "hiragana": "えき", "romaji": "Eki", "vietnamese": "Nhà ga" },
  { "japanese": "電話", "hiragana": "でんわ", "romaji": "Denwa", "vietnamese": "Điện thoại" },
  { "japanese": "家", "hiragana": "いえ", "romaji": "Ie", "vietnamese": "Nhà" },
  { "japanese": "家族", "hiragana": "かぞく", "romaji": "Kazoku", "vietnamese": "Gia đình" },
  { "japanese": "父", "hiragana": "ちち", "romaji": "Chichi", "vietnamese": "Bố (của mình)" },
  { "japanese": "母", "hiragana": "はは", "romaji": "Haha", "vietnamese": "Mẹ (của mình)" },
  { "japanese": "好き", "hiragana": "すき", "romaji": "Suki", "vietnamese": "Thích" },
  { "japanese": "大丈夫", "hiragana": "だいじょうぶ", "romaji": "Daijoubu", "vietnamese": "Không sao / Ổn" }
];
